[package]
name = "simple-magic"
version = "0.1.0"
authors = ["Isaac Grosof <isaacb227@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7"
